image: oven/bun:latest

pages:
  stage: deploy
  before_script:
    - apt-get update && apt-get install -y git
  script:
    - bun install
    - bun run build
    - mv build public
  artifacts:
    paths:
      - public
  only:
    - content
  variables:
    _REPO_NAME: $CI_PROJECT_NAME
    _REPO_OWNER: $CI_PROJECT_NAMESPACE
