services:
  mysql:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_SU_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  pgsql:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_PASSWORD: ${DB_SU_PASSWORD}
      POSTGRES_DB: ${DB_DATABASE}
    ports:
      - '5432:5432'
    volumes:
      - pgsql_data:/var/lib/postgresql

  dbx:
    image: t8y2/dbx:latest
    restart: always
    depends_on:
      - mysql
      - pgsql
    ports:
      - "4224:4224"
    environment:
      DBX_DISABLE_PASSWORD: "1"
    volumes:
      - dbx_data:/app/data

volumes:
  mysql_data:
  pgsql_data:
  dbx_data:
