services:
  mysql:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  dbx:
    image: t8y2/dbx:latest
    restart: always
    depends_on:
      - mysql
    ports:
      - "4224:4224"
    environment:
      DBX_DISABLE_PASSWORD: "1"
    volumes:
      - ./.dbx:/app/data

volumes:
  mysql_data: