services:
  mariadb:
    container_name: learn-mariadb
    image: mariadb:latest
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: ${MARIADB_ROOT_PASSWORD}
      MARIADB_DATABASE: ${MARIADB_DATABASE}
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  phpmyadmin:
    container_name: learn-phpmyadmin
    build:  
      context: ./.pma
      dockerfile: Dockerfile
    restart: always
    ports:
      - "8080:80"
    environment:
      PMA_HOST: mariadb
      PMA_USER: ${PMA_USER}
      PMA_PASSWORD: ${PMA_PASSWORD}
    volumes:
      - phpmyadmin_data:/var/lib/phpmyadmin

volumes:
  db_data:
  phpmyadmin_data: