"""
Watchdog is a python library to monitor filesystem events. like files/dirs are created, modified, or deleted.

In Linux It uses inotify, in mac uses FsEvents, In windows uses ReadDirectoryChangesW


THIS IS NOT IN STDLIB, INSTALL WITH PIP/UV

>> uv add watchdog

"""

import time
from typing import override

from watchdog.events import FileSystemEventHandler
from watchdog.observers import Observer

# There are two main classes: Observer and EventHandler
#
# - EventHandler: Contains callback logic that is called when a fs event is occurred
# - Observer: Runs in bg thread (os thread), watches paths, listens to the os.


# Usage:

# We create a Class inheriting FileSystemEventHandler and override methods.
# These methods contains callback logic.


class Watcher(FileSystemEventHandler):
    # Each trigger is a method that is called when a fs event is occurred
    #
    # - on_any_event:   Catch-all event handler
    # - on_created:     Called when a file or directory is created
    # - on_modified:    Called when a file or directory is modified
    # - on_deleted:     Called when a file or directory is deleted
    # - on_moved:       Called when a file or directory is moved or renamed
    # - on_closed:      Called when a file opened for writing is closed
    # - on_closed_no_write: Called when a file opened for reading is closed

    @override
    def on_created(self, event) -> None:
        # event is an instance of FileSystemEvent, it has following attributes:
        #
        # - event_type = Type of event (created, modified, deleted, moved)
        # - src_path   = the path where the event occurred
        # - dest_path   = (only for moved events) Destination path
        # - is_directory = True if the event occurred on a directory, False otherwise
        # - is_synthetic = True if the event is not broadcasted by os's kernal due to raw change, rather generated by watchdog itself
        #
        print(f"Created: {event.src_path}")

    # Called when a file or directory is moved or renamed
    @override
    def on_moved(self, event) -> None:
        print(
            "Dir" if event.is_directory else "File",
            f"moved: {event.src_path} -> {event.dest_path}",
        )


if __name__ == "__main__":
    observer = Observer()

    # schedule & start the listener
    observer.schedule(Watcher(), ".", recursive=True)  # pyright: ignore[reportUnusedCallResult]

    observer.start()
    print("Started observer...")

    #  why do we need the infinite loop?
    #  we need to keep the program running so the observer can keep listening for events
    try:
        while True:
            time.sleep(1)
    except KeyboardInterrupt:
        observer.stop()  # signal to stop

    observer.join()  # wait for the observer to stop
